-- Apartment Management System Database Schema

-- Users table
CREATE TABLE IF NOT EXISTS NguoiDung (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TenDangNhap VARCHAR(100) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    SoDienThoai VARCHAR(20),
    VaiTro ENUM('ChuNha', 'NguoiThue', 'QuanLy') DEFAULT 'NguoiThue',
    TrangThai VARCHAR(50) DEFAULT 'Active',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Buildings table
CREATE TABLE IF NOT EXISTS ToaNha (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TenToaNha VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,
    ThanhPho VARCHAR(100) NOT NULL,
    TrangThai VARCHAR(50) DEFAULT 'Active'
);

-- Apartments table
CREATE TABLE IF NOT EXISTS CanHo (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MaCanHo VARCHAR(50) UNIQUE NOT NULL,
    Tang INT,
    SoPhong VARCHAR(50),
    DienTich DECIMAL(10, 2),
    GiaThue DECIMAL(15, 2),
    TienCoc DECIMAL(15, 2),
    TrangThai VARCHAR(50) DEFAULT 'Trong',
    MoTa TEXT,
    ChuNhaID INT NOT NULL,
    ToaNhaID INT,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ChuNhaID) REFERENCES NguoiDung(ID),
    FOREIGN KEY (ToaNhaID) REFERENCES ToaNha(ID)
);

-- Contracts table
CREATE TABLE IF NOT EXISTS HopDong (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MaHopDong VARCHAR(50) UNIQUE NOT NULL,
    CanHoID INT NOT NULL,
    NguoiThueID INT NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE,
    TrangThai VARCHAR(50) DEFAULT 'Active',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CanHoID) REFERENCES CanHo(ID),
    FOREIGN KEY (NguoiThueID) REFERENCES NguoiDung(ID)
);

-- Invoices table
CREATE TABLE IF NOT EXISTS HoaDon (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MaHoaDon VARCHAR(50) UNIQUE NOT NULL,
    HopDongID INT NOT NULL,
    NgayPhatHanh DATE NOT NULL,
    SoTien DECIMAL(15, 2),
    TrangThai VARCHAR(50) DEFAULT 'Pending',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (HopDongID) REFERENCES HopDong(ID)
);
